Feature reset state
iotaledger/streams pull request #113
Opened 2021-07-14 22:15 UTC by DyrellC

# Description of change
Add `reset_state` function to subscribers to allow subscribers to fetch messages from scratch without restarting their instance. 

Example: 
```
subscriber.reset_state()?;
let msgs = subscriber.fetch_all_next_msgs();
```

Bindings and  docs have been updated as well. 

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
New section in examples demonstrating usage in rust, c and wasm.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-15 07:13 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/user.rs
> +                self.pk_store = pk_store;
Looks like a dirty hack. Currently, User state contains two kinds of objects: permanent - keys, settings, etc., and ephemeral - current index within channel (ie. cursor for all known users). This index is stored in pk_store that serves these two purposes: it contains public keys and associated cursor. It begs to be split in two: just public keys and such index. This index then can be made an external object that can be manipulated more easily.

2021-07-15 14:19 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +                self.pk_store = pk_store;
What would be your proposition for resetting state then if not to literally reset it in this fashion? The pk_store needs to be put back to the starting state in order to facilitate syncing from scratch, which means the cursors need to be reset to the starting point for all publishers. Technically it could be done by only including the author pk and setting it the same way receiving an announcement would, and once the subscriber hits the keyloads they'll re-enter any other publishers in the standard way, but that just postpones the placement of those pk/cursor mappings until then, it doesn't actually change the behaviour at all?

2021-07-16 15:09 UTC, kwek20 requested changes

2021-07-16 15:09 UTC, kwek20 commented on docs/libraries/wasm/api_reference.md
> +#### get_seq_no()
typo here, still says seq

2021-07-30 14:48 UTC, DyrellC commented on docs/libraries/wasm/api_reference.md
> +#### get_seq_no()
Tis done

2021-07-30 14:57 UTC, merged