Feature: remove async flag, make api async by default
iotaledger/streams pull request #136
Opened 2021-08-06 20:59 UTC by DyrellC

# Description of change
Update functionality to remove double api in channels. Removes the `async` flag altogether and places more reliance on `sync-client` flag instead. C bindings have been updated but wasm still has yet to be tested due to the `iota.rs` wasm `mio` issue (should be resolved soon).

ToDo:
- [ ] Update wasm bindings once the `iota.rs` bug is resolved
- [ ] Update any relevant docs 
- [ ] Pull in spongos updates as well as Arnau's lint review

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
-  iota_streams/examples
-  iota-streams-examples 
-  c bindings example tested, only one that doesn't work is static build with client on, because corrosion doesn't accept feature flags right now

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-11 11:46 UTC, semenov-vladyslav reviewed
Looks good but there are a few places that need clarification.

2021-08-11 11:46 UTC, semenov-vladyslav commented on bindings/c/src/api/mod.rs
> +    let ret = tokio::runtime::Runtime::new().unwrap().block_on(fut);
Is it OK to always create a new Runtime?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/user.rs
> +    async fn transport_recv(&mut self, link: &Address) -> Result<Message> {
Git diff is super weird, it decided that it's a proper place to add these two lines between these big chunks of removed code.

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/message/content.rs
> +    async fn sizeof<'c>(&self, ctx: &'c mut sizeof::Context<F>) -> Result<&'c mut sizeof::Context<F>>;
Why exactly this should be `async`? It's supposed to be a pure function.

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/message/prepared.rs
> +    store: &'a Arc<Mutex<Store>>,
Shall we abstract `Arc<Mutex<..>>` away somehow? Or maybe even add constraints to `LinkStore` trait so thread-safety is guaranteed?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/message/announce.rs
> +        &'c mut self,
I'm not sure it has to be the same life-time for `&mut self` and `store: &Store` as for `ctx` and result type. But if it works then fine.

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/message/keyload.rs
> +        let saved_fork = ctx.spongos.fork();
What is the issue with `fork`? Why workaround is needed?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/message/prepared.rs
> +    Content: ContentWrap<F, Store> + Send + Sync,
Maybe add `Send + Sync` constraints to all these traits `ContentWrap`, `LinkStore`, `HasLink`, etc.?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/transport/bucket.rs
> +#[cfg(feature = "sync-client")]
Why constraint here? `TransportOptions` can be implemented for `BucketTransport` anyway, can't it?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/transport/mod.rs
> +impl<Tsp: TransportOptions + Send + Sync> TransportOptions for Arc<Mutex<Tsp>>
Is `Mutex` better than `AtomicRefCell`?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/transport/mod.rs
> +#[cfg(feature = "sync-client")]
Once again, maybe just get rid off of `sync-client` feature and this version (non-async) of `Transport`?

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-app/src/transport/tangle/client.rs
> +#[cfg(feature = "sync-client")]
No `sync-client` feature, no `block_on`s, no problems. Profit

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-ddml/src/command/wrap/fork.rs
> +    C: for<'a> FnMut(&'a mut Self) -> Result<&'a mut Self> + Send,
Why is this `fork` not used in wrap/unwrap context? Constraint on `C` should be something like `for<'a> async FnMut(..) ..` or `async` can be made explicit in the result type: `for<'a> FnMut(..) -> Future<Output = Result<..>>`

2021-08-11 11:46 UTC, semenov-vladyslav commented on iota-streams-ddml/src/command/wrap/fork.rs
>      fn fork(&mut self, mut cont: C) -> Result<&mut Self> {
`fork` method should definitely be `async` if we allow async Wrap/Unwrap traits.

2021-08-12 15:13 UTC, DyrellC commented on bindings/c/Cargo.toml
> +std = ["iota-streams/std", "iota-streams/async-client"]
Ah yes, definitely the better way to be doing that

2021-08-12 15:15 UTC, DyrellC commented on bindings/c/src/api/auth.rs
> +pub async unsafe extern "C" fn auth_receive_signed_packet(
Nah it's a remnant from experimenting with different approaches (specifically from when there wasn't a utility function for running asynchronous code so each function was doing it individually with awaits etc).

2021-08-12 15:16 UTC, DyrellC commented on bindings/c/src/api/auth.rs
> +                return user.receive_signed_packet(link).await.map_or(Err::OperationFailed, |signed_payloads| {
It should indeed be `run_async`

2021-08-12 15:21 UTC, DyrellC commented on bindings/c/src/api/mod.rs
> +    let ret = tokio::runtime::Runtime::new().unwrap().block_on(fut);
There are 2 options really: 
1. Create a new runtime each time we run a function 
2. Wrap author instance with a stored runtime inside it and spawn blocking from it every time we need to use a call to send/receive 

It is necessary to have a tokio runtime if we are using the iota.rs client, that much is certain

2021-08-12 15:34 UTC, DyrellC commented on iota-streams-app-channels/src/message/announce.rs
> +        &'c mut self,
There was a compiler complaint at some point that was pushing for me to set the lifetime for self as well, but it looks like it's not complaining about it anymore so i'll remove it for now, because I agree it shouldn't need the same constraint

2021-08-12 15:35 UTC, DyrellC commented on iota-streams-app-channels/src/message/keyload.rs
> +        let saved_fork = ctx.spongos.fork();
Fork won't let me insert async functions, neither will repeated, it creates lifetime conflicts that I was unable to find a workaround for.

2021-08-12 15:36 UTC, DyrellC commented on iota-streams-app/Cargo.toml
> +async-client = ["num_cpus", "iota-client/default", "tangle", "std"]
I was going to ask the same thing to everyone, I think it's an unnecessary feature at this time unless we plan to separate the client functionality to actually allow for sending the messages asynchronously, but since that's not present at the time it's just superfluous and bloats the code base.

2021-08-12 15:38 UTC, DyrellC commented on iota-streams-app/src/message/content.rs
> +    async fn sizeof<'c>(&self, ctx: &'c mut sizeof::Context<F>) -> Result<&'c mut sizeof::Context<F>>;
These functions are going to need to be async to accommodate the DID functionality since everything on that end is asynchronous. It's either `block_on`'s or an async trait.

2021-08-12 15:39 UTC, DyrellC commented on iota-streams-app/src/message/prepared.rs
> +    store: &'a Arc<Mutex<Store>>,
Seems a reasonable thing to do. Where were you thinking? Just in `message/mod.rs`?

2021-08-12 15:39 UTC, DyrellC commented on iota-streams-app/src/message/prepared.rs
> +    Content: ContentWrap<F, Store> + Send + Sync,
Yeah the thought crossed my mind. Would save on all these extra trait definitions everywhere

2021-08-12 15:47 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
> +impl<Tsp: TransportOptions + Send + Sync> TransportOptions for Arc<Mutex<Tsp>>
In hindsight perhaps not, originally it was the mutex from futures since we were already loading it in, but now it uses spin (since it's lightweight and `no_std` ready) so it's worth discussing the options

2021-08-12 15:48 UTC, DyrellC commented on iota-streams-app/src/transport/tangle/client.rs
> +#[cfg(feature = "sync-client")]
Right? Think it's better to just remove it entirely as you suggested. I was going to suggest the same thing for now

2021-08-12 15:48 UTC, DyrellC commented on iota-streams-ddml/src/command/wrap/fork.rs
> +    C: for<'a> FnMut(&'a mut Self) -> Result<&'a mut Self> + Send,
I tried the second option and ran into a bunch of lifetime headaches (especially in `api/user.rs`)

2021-08-19 16:57 UTC, sascha1337 commented on iota-streams-app/Cargo.toml
> +async-client = ["num_cpus", "iota-client/default", "tangle", "std"]
Please go for it :) It would make the debugging and everything so much easier, with that less complexity and less feature deps chaining. It really confused not only me :P

2021-09-01 11:17 UTC, arnauorriols commented
> Enhancement (a non-breaking change which adds functionality)
How come you consider it a non-breaking change? I'd say it's a pretty significant breaking change...

2021-09-01 13:58 UTC, kwek20 commented
haha and also mainly removes functionality, not adds it :D

2021-09-01 14:08 UTC, DyrellC commented
> > Enhancement (a non-breaking change which adds functionality)
> 
> How come you consider it a non-breaking change? I'd say it's a pretty significant breaking change...

Oh that's definitely a typo. I meant to remove the `non-breaking change` part of that but obviously did not

2021-09-01 14:35 UTC, DyrellC commented on iota-streams-ddml/src/command/wrap/fork.rs
> +    C: for<'a> FnMut(&'a mut Self) -> Result<&'a mut Self> + Send,
Saving the fork and repeated for a different pr

2021-09-01 18:43 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
> +// async fn send_message(&mut self, msg: &Msg) -> Result<()>;
Definitely dead code remnants. I'm removing them.

2021-09-03 14:17 UTC, arnauorriols requested changes
This is a first batch of comments. I have a couple of stashed issues that I want to make sure are feasible to improve before proposing. 

Overall, this PR is a very significant improvement in terms of design, amazing job!

2021-09-03 15:33 UTC, DyrellC commented on iota-streams-core/Cargo.toml
> +spin = { version = "0.9.2", default-features = false, features = ["mutex", "spin_mutex"] }
Caught in the fallacy that it would be a reasonable `#[no-std]` compatible replacement, thanks for the reading material. I was hoping to use just one implementation if possible but i'll work on replacing that.

2021-09-03 17:47 UTC, DyrellC commented on iota-streams-core/Cargo.toml
> +futures = { version = "0.3.8", default-features = false, features = ["executor"] }
For `async-trait` it was so it could be accessed from ddml, `futures` was just sort of along for the ride. I'm moving `futures` back but i'm going to keep `async-trait` where it is to tackle to the `repeated/fork` issue in a different PR.

2021-09-03 17:48 UTC, DyrellC commented on iota-streams-core/Cargo.toml
> +no-std = []
Yup, removing

2021-09-03 17:49 UTC, DyrellC commented on iota-streams-core/src/sponge/prp/prp.rs
> +pub trait PRP: Sized + Default + Clone + Send + Sync //+ From<Vec<u8>> + Into<Vec<u8>>
I'm ok with going the `(?Send)` route, I just hope it doesn't make some new headaches in the DID realm. I don't suspect it will but you never know dealing with async stuff in rust :man_shrugging:

2021-09-03 17:49 UTC, DyrellC commented on iota-streams-core/src/sponge/prp/prp.rs
> +pub trait PRP: Sized + Default + Clone + Send + Sync //+ From<Vec<u8>> + Into<Vec<u8>>
I'll get that merged in after I've wrapped up a couple other changes here

2021-09-03 17:49 UTC, DyrellC commented on iota-streams-ddml/src/command/wrap/fork.rs
> +        cont(&mut *self)?;
Remnant from async fork and repeated experiments, i'll revert it back

2021-09-03 17:52 UTC, DyrellC commented on iota-streams-app/src/message/wrapped.rs
>      /// Save link for the current wrapped message and associated info into the store.
Not sure I follow on this one? What are you referring to specifically?

2021-09-03 17:58 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
> +pub type SharedTransport<T> = Rc<RefCell<T>>;
Yeah it hasn't been used anywhere, I think it's reasonable to remove it

2021-09-03 18:02 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
>  pub trait TransportOptions {
Probably not really, I'll go ahead and remove it provided compilation doesn't give me any grief doing so.

2021-09-03 18:11 UTC, DyrellC commented on iota-streams-app/src/message/content.rs
> +        store: &'c Store,
Keyload was giving grief at some point and then it just got left the way it was. Looks like the compiler isn't spitting out the same errors anymore, so I'll revert it back

2021-09-03 19:01 UTC, DyrellC commented on iota-streams-app/src/message/preparsed.rs
> +        store: &MutexGuard<'_, Store>,
I like that, i'll have to make a few extra little changes to accommodate it though

2021-09-03 19:01 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
>  pub trait TransportOptions {
It is not, changed now

2021-09-03 19:04 UTC, DyrellC commented on iota-streams-app-channels/src/message/keyload.rs
> +            ctx.absorb(repeated_keys)?;
I was using it for my own reference but they're pretty pointless now. Removing

2021-09-03 19:06 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +            let ctx = id.clone().wrap(_store.borrow(), ctx.borrow_mut()).await?;
Yeah that underscores been there since the ancient days lol I'll fix that up

2021-09-03 19:07 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/author.rs
> +        #[cfg(not(feature = "sync-client"))]
The merge must have left that in there I definitely remember correcting this at one point.

2021-09-03 19:07 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/author.rs
> +        #[cfg(not(feature = "sync-client"))]
hurray for rebase right?

2021-09-03 19:09 UTC, DyrellC commented on bindings/c/Cargo.toml
> +tokio = {version = "1.9.0", features = ["rt", "rt-multi-thread"]}
We need tokio no matter which implementation we use. It's part of the global runtime we have to set up for the `run_async` wrapper function

2021-09-03 23:12 UTC, arnauorriols commented on iota-streams-app/src/message/wrapped.rs
>      /// Save link for the current wrapped message and associated info into the store.
Oh, I understand now. it was regarding the `accociated` instead of `associated` somehow I saw that in your PR you were introducing the typo to an already correctly written word, but now I believe that was a git conflict resolution gone wrong. Nevermind 😅

2021-09-07 16:44 UTC, arnauorriols commented on bindings/c/Cargo.toml
> +tokio = {version = "1.9.0", features = ["rt", "rt-multi-thread"]}
Yeah, you are right. I was thinking in terms of "we only need async for the transport client" but as long as even DDML is `async`, `tokio` goes with us to the bone...

2021-09-07 16:51 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/author.rs
> +        #[cfg(not(feature = "sync-client"))]
I figured as much 😅

2021-09-07 19:17 UTC, arnauorriols commented
So, I've been experimenting with my couple of pending issues, and have pushed DyrellC/streams#3 

In summary, I had the suspicion that the interior mutability (and now synchronized mutation) was at least not a necessity, and in my opinion not justified given the nature of the library. I've managed to remove the synchronization both in the `LinkStore` and in the bindings. Synchronization has a significant impact in performance and embedded compatibility (for example, espidf target, while implementing std, don't support any locking mechanism), therefore I think it's worth its removal if possible.

2021-09-07 19:25 UTC, DyrellC commented
> support

I agree, it seems excessive to be accommodating for a use case that will never be. The only instance of asynchronous functionality that should be accommodated imo is the ability to asynchronously transport the message without waiting on the response but there are other accomodations necessary before we go down that path so we'll save that for the future.

2021-09-07 23:02 UTC, arnauorriols approved these changes

2021-09-07 23:08 UTC, merged