Feature: Single Depth Channels
iotaledger/streams pull request #139
Opened 2021-08-16 23:33 UTC by DyrellC

# Description of change
Add the third implementation type to Channels. This is the `SingleDepth` implementation. It allows a single publisher (the Author) to send messages that, instead of chaining, surround a single anchor message and can be retrieved by a corresponding sequence number. The retrieval method has been added and can be used like so: 
Rust:
```Rust
let msg = subscriber.receive_msg_by_sequence(anchor_link, msg_num)?;
match msg.body {
    MessageContent::SignedPacket { pk, public_payload, masked_payload } => { ... }, 
    MessageContent::TaggedPacket { public_payload, masked_payload } => { ... }, 
    _ => { Err(...) } // You should only be processing tagged and signed packets
}
```
C:
```C
unwrapped_message_t const *message_return = NULL;
err = auth_receive_msg_by_sequence(&message_return, author, anchor_link, msg_num);
if(e) { 
      printf("Error code: %d\n", e); 
} else { 
    packet_payloads_t response = get_payload(message_return);
    printf("Public: '%s'\n", response.public_payload.ptr);
    printf("Masked: '%s'\n", response.masked_payload.ptr);
}
```

WASM:
```JS
let response = await sub.clone().receive_msg_by_sequence(anchor_link, msg_num);
let msg = response.get_message();
let public_payload = msg.get_public_payload();
let masked_payload = msg.get_masked_payload();
```

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
A new example has been added to the examples section to demonstrate/test behaviour

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-29 20:27 UTC, kwek20 approved these changes

2021-08-31 10:23 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user.rs
> +                // Subtract 1 from the sequence number so users can start from 1 instead of 0
Users are programmers themselves. There's a general assumption among programmers that sequences start from 0, right?

If it is 1, as a user I would appreciate it being explicitly documented

2021-08-31 12:10 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user.rs
> +                let link = self.user.link_gen.link_from(&(*pk).into(), cursor);
This operation copies the `pk` every time, to wrap it into an `Identifier`. This also happens in other places as well. Not proposing to change it necessarily now, but: wouldn't it be more interoperable if `LinkGenerator::link_from` took `AsRef<[u8]>` instead of `&Identifier` for the id? Does `LinkGenerator` really have to concern with what is specifically used as identifier?

2021-08-31 12:37 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/subscriber.rs
> +        if self.is_single_depth() {
+1. It has a significant UX consequence in that those errors should be compile errors and not runtime errors as they are. There are some methods that return `Result` just for this reason, and shouldn't return `Result` at all. I've noted it in my project review notes and at some point I plan to propose a refactor if not done already by then.

2021-08-31 12:48 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +                println!("Adding seq no {}", seq_no.0);
Leftover?

2021-08-31 13:03 UTC, arnauorriols requested changes
Good to go from my side, except for these 2 points:
- [why only Author](https://github.com/iotaledger/streams/pull/139/files#r697464915)
- [why start from 1](https://github.com/iotaledger/streams/pull/139/files#r699189443)

and [the println! leftover](https://github.com/iotaledger/streams/pull/139/files#r699288598)

2021-09-01 19:40 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/subscriber.rs
> +        if self.is_single_depth() {
As discussed yesterday we'll leave this as is for now and refactor the logic at another time

2021-09-01 20:38 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> +                let link = self.user.link_gen.link_from(&(*pk).into(), cursor);
Yes that does make sense, it would be nice to find a means of making `AsRef<[u8]>` for an `Identifier` but I don't think we'll be able to do so without modifying `Identifier` to not be an enum (or at least stick the type as an enum within a struct with a `Vec<u8>` field) otherwise we will always need to create a new byte vector each time we want to use it instead of just referencing internal fields. Something to consider.

I'll make the `link_from()` change for now and we can consider how to approach the `Identifier` in another PR.

2021-09-01 20:57 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> +                // Subtract 1 from the sequence number so users can start from 1 instead of 0
It's back to starting from 0 now

2021-09-02 16:34 UTC, arnauorriols approved these changes
Good to go!

2021-09-02 16:47 UTC, merged