Feat/update sub unsub processes
iotaledger/streams pull request #145
Opened 2021-09-08 20:34 UTC by DyrellC

# Description of change
Addition of utility functions to aid in subscription and unsubscription. This includes reintroducing the `Unsubscribe` message type as well as adding functions to the `Author` allowing them to manually predefine and remove subscribers from a channel. 

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
- [x] single branch test has been modified to include author side manual subscription and removal of subscriber A, as well as having subscriber B send an unsubscribe message that is read by 
- [ ] wasm bindings have been updated along with the same manual sub/unsub from the author in the examples
- [ ] c bindings have been updated along with the same manual sub/unsub from the author in the examples
- [x] all other examples continue to work without being impeded
- [x] checked that state was updated on the author end when subscribers removed (currently no functionality to have those users states removed from other subscribers states) 

## Change checklist
- [] I have followed the contribution guidelines for this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2021-09-14 15:40 UTC, arnauorriols requested changes
Finished the review. Besides some minor comments to improve idiomacy, the major comment I've left is regarding the `ubsubscribe_key` in [`unsubscribe.rs`](https://github.com/iotaledger/streams/pull/145#discussion_r708531819)

2021-09-14 15:40 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +        )
A more idiomatic way to write the same:
```suggestion
        public_key_from_string(&pk_str)
            .and_then(|pk| self.author.borrow_mut().store_new_subscriber(pk))
            .into_js_result()
```

2021-09-14 15:40 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +        )
This applies also to the other similar methods

2021-09-14 15:40 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +    #[wasm_bindgen(catch)]
this applies to the other methods as well

2021-09-14 15:40 UTC, arnauorriols commented on examples/src/branching/single_branch.rs
> +
I would add some lines that test that unsubscribe actually works

2021-09-14 15:40 UTC, arnauorriols commented on iota-streams-app-channels/src/api/key_store.rs
> +    fn remove(&mut self, id: &Identifier) -> Result<()>;
What's the reasoning behind returning a `Result` here? I could imagine it's meant to support external key-stores, but then all methods should return `Result`...

I wonder the same for the other methods of this trait that return `Result` TBH.

2021-09-14 15:40 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +        let id = (*pk).into();
It's customary to let the user of a method decide if a value needs copying/cloning. In other words, if a function needs ownership, it should ask the parameter by value instead of copying/cloning internally. In this case, as PublicKey is `Copy`, it would actually clean up the syntactic noise of the borrow and the dereference.

2021-09-14 15:40 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +        self.key_store.remove(&(*pskid).into())
Idem, just take `PskId` by value

2021-09-14 15:40 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +        let id = (*pk).into();
See https://rust-lang.github.io/api-guidelines/flexibility.html#c-caller-control

2021-09-14 15:54 UTC, DyrellC commented on bindings/wasm/src/author/authorw.rs
> +    core::psk::pskid_from_hex_str,
They should indeed. Updating now

2021-09-14 18:23 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +        // Unwrapped unsubscribe_key is not used explicitly.
What's the deal with the unsubscribe_key then? Why aren't we using as ["the password to unsubscribe from the channel"](https://github.com/iotaledger/streams/blob/develop/iota-streams-app-channels/src/message/subscribe.rs#L30)?

2021-09-14 18:35 UTC, arnauorriols commented on iota-streams-app-channels/src/message/unsubscribe.rs
> +            .ed25519(self.sig_kp, HashSig)?;
The public key of the subscribers is masked in the `Subscribe` message, but it becomes shared to the other subscribers in the `Keyload` messages. The `unsubscribe_key` is the only key that remains private to the subscriber and the author, therefore if we don't use it at all in here, what's stopping any other user of the channel to forge an `Unsubscribe` message on behalf of another one?

2021-09-14 19:00 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        // Unwrapped unsubscribe_key is not used explicitly.
Solid question, one I have yet to get an answer from Vlad on. Unsubscribe was removed a long time ago, back before there was a proper signature pair for subscribers, so any logic related to the unsubscribe key used to be based off the spongos state of the unsubscribe message, and verification using a MAC, but now that we have proper signature scheme there's a bit of a toss up on requirement here. 

I don't have a problem with storing the password and using it as access, but the question becomes:  is it necessary to do so if the unsubscribe messages are being signed by the subscriber in the first place? Does the unsubscribe key serve a genuine purpose anymore now that the keypairings are actually being used for verification purposes? 

If not then I think it's a reasonable thing to remove the unsubscribe key altogether, but if it's considered a valuable thing to have, then we need to store that locally, and a password needs to be mapped on the Author end to do a match comparison for manual unsubscription, which may complicate things unnecessarily. I'm open for discussion on the topic though, for now I was more focused on updating the logic to be compatible again as a message type.

2021-09-14 19:04 UTC, DyrellC commented on iota-streams-app-channels/src/message/unsubscribe.rs
> +            .ed25519(self.sig_kp, HashSig)?;
I think the simple answer to that is that the unsubscribe messages are signed by the subscriber instance, and knowing the public key doesn't mean that a user can fake a signature representing that subscriber themselves. If anything i'm more sceptical of the requirement for an unsubscribe key but didn't want to focus too hard on changing the existing logic/internal mechanisms of subscription/unsubscription too much during this iteration

2021-09-14 20:05 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        let id = (*pk).into();
Fair points (for this and the public key comment above), I'll update these.

2021-09-14 20:13 UTC, DyrellC commented on iota-streams-app-channels/src/api/key_store.rs
> +    fn remove(&mut self, id: &Identifier) -> Result<()>;
For this particular remove function, it is pretty unnecessary, I had more logic going on in there at some point and looks like although the logic was removed, the result wasn't, so i'll remove it for now. 

As for the other  functions though, the main reason is due to the possibility of a user trying to make logic that uses an incorrect `Identifier`, for example if a user tries to `insert_psk` with an `Identifier::EdPubKey` it returns an error to inform the user that that operation can't be completed using the Identifier type they've injected. This separation of `Idenitifier` insertions is necessary (at least for now) due to the difference in cursor storage for each type. It would be good to unify them though, then we could avoid the need altogether.

2021-09-14 20:23 UTC, DyrellC commented on examples/src/branching/single_branch.rs
> +
Done

2021-09-14 20:23 UTC, DyrellC commented on bindings/wasm/src/author/authorw.rs
> +        )
I've updated them

2021-09-14 20:23 UTC, DyrellC commented on bindings/wasm/src/author/authorw.rs
> +    #[wasm_bindgen(catch)]
I've updated these as well

2021-09-14 23:07 UTC, arnauorriols commented on iota-streams-app-channels/src/message/unsubscribe.rs
> +            .ed25519(self.sig_kp, HashSig)?;
Of course. I was myself pulling backwards from the assumption that there was a reason for the `unsubscribe_key` to begin with.

2021-09-14 23:11 UTC, arnauorriols commented on iota-streams-app-channels/src/api/user.rs
> +        // Unwrapped unsubscribe_key is not used explicitly.
Very Reasonable. While we wait for @semenov-vladyslav input on this (for a while at least) before taking action, let's change this comment and put a clear `// TODO: remove unused unsubscribe_key because ...`

2021-09-15 14:46 UTC, arnauorriols approved these changes

2021-09-16 17:00 UTC, merged