Feat/wasm: authentication & perma node
iotaledger/streams pull request #149
Opened 2021-09-15 18:39 UTC by kwek20

# Description of change

Adds the iots.rs builder options to the WASM bindings

## Type of change
- Enhancement (a non-breaking change which adds functionality)
-
## How the change has been tested

ran nodejs, nodets and web examples

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-09-16 16:59 UTC, DyrellC requested changes
I think it makes more sense to put the client builder options inside the rust side of things and then map the bindings to the wrapper functions like we do the `TransportDetails` that way we can map the functionality into wasm and c without having to rewrite them custom for each. There's also the matter of the renaming of the library outputs. Otherwise I like the way the pattern works, very succinct.

2021-09-16 16:59 UTC, DyrellC commented on bindings/wasm/Cargo.toml
> +name = "streams_wasm"
Are we reverting this back now?

2021-09-16 16:59 UTC, DyrellC commented on bindings/wasm/src/user/builder.rs
> +#![allow(clippy::unnecessary_wraps)]
Where's the unnecessary wrap that this is here for? Do we want to be introducing new clippy circumvention right after fixing up a bunch of them?

2021-09-16 16:59 UTC, DyrellC commented on bindings/wasm/src/user/builder.rs
> +pub struct ClientBuilder(ClientBuilderRust);
Does it make sense for us to provide this pattern through Wasm and C individually like this but not through rust? Would it make sense to migrate the Client Builder wrapper functions over to `iota-streams-app/src/transport/tangle/` somewhere so that they can be accessed by all 3 implementations instead?

2021-09-16 17:11 UTC, kwek20 commented on bindings/wasm/Cargo.toml
> +name = "streams_wasm"
thats not reverting!! its supposed to be like that :P idk why it got reverted earlier.
Else NPM has @iota/iota-streams/wasm
that just seems silly :D

2021-09-16 17:12 UTC, kwek20 commented on bindings/wasm/src/user/builder.rs
> +#![allow(clippy::unnecessary_wraps)]
Oh no, how did that get in there? D:

2021-09-16 17:13 UTC, kwek20 commented on bindings/wasm/src/user/builder.rs
> +pub struct ClientBuilder(ClientBuilderRust);
Huh? it is accessible through rust, you just use iota.rs Client builder. So we dont need to have our own copy

2021-09-16 17:25 UTC, DyrellC commented on bindings/wasm/Cargo.toml
> +name = "streams_wasm"
Maybe the earlier reverting was done during Arnau's cleanup refactor a couple weeks back, that checks out then, you can ignore me :stuck_out_tongue:

2021-09-16 17:25 UTC, DyrellC commented on bindings/wasm/src/user/builder.rs
> +#![allow(clippy::unnecessary_wraps)]
:scream:

2021-09-16 17:27 UTC, DyrellC commented on bindings/wasm/src/user/builder.rs
> +pub struct ClientBuilder(ClientBuilderRust);
Ah No you're right, I forgot about `Client::new(options: SendOptions, client: iota_client::Client)` since we default to using `new_from_url(url: &str)` so often. I guess all that's needed then is as you said before: making a similar abstraction wrap through the c side... fun fun.

2021-09-21 19:48 UTC, arnauorriols requested changes
First batch of review comments. They are mostly cosmetic, except for the more essential one regarding whether aren't we reimplementing the `ClientBuilder` bindings from iota.rs.

2021-09-21 19:48 UTC, arnauorriols commented on bindings/wasm/src/user/builder.rs
> +pub struct ClientBuilder(ClientBuilderRust);
Aren't we... reimplementing the wasm-bindings of the iota.rs `ClientBuilder`? Why do we need to do that?

2021-09-21 19:48 UTC, arnauorriols commented on bindings/wasm/src/user/userw.rs
> +pub fn new_with_client(iota_client: RustClient, options: SendOptions) -> Client {
Why not a constructor? as in `Client::new_with_client(...)`, not need to make it a js constructor obviously

2021-09-21 19:48 UTC, arnauorriols commented on bindings/wasm/src/user/builder.rs
> +    #[wasm_bindgen(catch)]
All those `catch` don't belong here, they are used for imported js functions, not exported rust functions

2021-09-27 10:19 UTC, arnauorriols requested changes
Adding a couple of comments in builder.rs

2021-09-30 15:27 UTC, arnauorriols requested changes
Some comments on the new version that reuses `iota.rs`

2021-09-30 15:27 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +        let api_client = ApiClient::new_from_client(client.to_inner());
as per https://rust-lang.github.io/api-guidelines/naming.html#c-conv: 
`client_wasm::Client::to_inner()` should be `client_wasm::Client::into_inner()`

2021-09-30 15:27 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +        let api_client = ApiClient::new_from_client(client.to_inner());
using `iota_client::Client::clone(&client.into_inner())` we can avoid polluting `ApiClient` with `Rc`, which is a `wasm` artefact.

2021-09-30 15:27 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +    pub fn from_client_rs(client: RustWasmClient, seed: String, implementation: ChannelType) -> Author {
I would stick with `fromClient()` constructor, because `fromClientRs()` is quite obscure, specially from a javascript point of view. I cannot think of a better name, and for consistency with `import()` and `get_client()`, it make sense that `Author` API only deals with `StreamsClient`

2021-09-30 15:27 UTC, arnauorriols commented on bindings/wasm/src/types/mod.rs
> +pub enum Api {
This is unused now

2021-09-30 15:27 UTC, arnauorriols commented on bindings/wasm/src/user/userw.rs
> +pub fn new_with_client(iota_client: RustClient, options: SendOptions) -> StreamsClient {
This should be an static method of `StreamsClient` and accept `RustWasmClient` instead of `RustClient`

2021-09-30 15:27 UTC, arnauorriols commented on iota-streams-app/src/transport/tangle/client.rs
> +    client: Rc<iota_client::Client>,
Cloning `iota_client::Client` in `wasm` we should be able to avoid adding `Rc` here

2021-09-30 15:44 UTC, arnauorriols commented on bindings/wasm/package.json
> +    "@iota/client-wasm": "^0.1.2",
not needed

2021-09-30 16:13 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +    pub fn from_client_rs(client: RustWasmClient, seed: String, implementation: ChannelType) -> Author {
Pushed in a PR to this branch

2021-09-30 16:13 UTC, arnauorriols commented on bindings/wasm/package.json
> +    "@iota/client-wasm": "^0.1.2",
pushed in a PR to this branch

2021-09-30 16:14 UTC, arnauorriols commented on iota-streams-app/src/transport/tangle/client.rs
> +    client: Rc<iota_client::Client>,
pushed in a PR to this branch

2021-09-30 16:14 UTC, arnauorriols commented on bindings/wasm/src/user/userw.rs
> +pub fn new_with_client(iota_client: RustClient, options: SendOptions) -> StreamsClient {
pushed in a PR to this branch

2021-09-30 16:14 UTC, arnauorriols commented on bindings/wasm/src/types/mod.rs
> +pub enum Api {
pushed in a PR to this branch

2021-09-30 16:16 UTC, arnauorriols commented on bindings/wasm/src/user/userw.rs
> +pub fn new_with_client(iota_client: RustClient, options: SendOptions) -> Client {
pushed in a PR to this branch

2021-09-30 17:32 UTC, arnauorriols approved these changes

2021-10-01 08:31 UTC, arnauorriols commented on iota-streams-core/src/sponge/spongos.rs
> +    pub fn into_inner(&self) -> Result<Inner<F>> {
you went a bit overboard with this change 😂  the gist is:
- **from non-copy owned to owned: `into_`**. 
  - Conveys that the receiver (`self`) is being consumed
- **from ref to owned: `to_`**
  - Conveys that we are getting owned stuff without taking ownership of the receiver (which is usually implemented expensively cloning data)
- **from ref to ref: `as_`**
  - Conveys that we are just getting a view into some internal data, no expensive conversions are made

2021-10-01 08:31 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +            },
you need to run `cargo +nightly fmt`

2021-10-01 15:49 UTC, DyrellC approved these changes
Overall looks good, added a couple small comments, mostly things that we'll deal with outside of this PR. Just need to resolve the conflicts and she looks good to go.

2021-10-01 15:49 UTC, DyrellC commented on bindings/wasm/Cargo.toml
> +name = "streams_wasm"
Just going to add my 2 cents here, doesn't need to change in this PR specifically but I think it makes sense to rename to `@iota/streams` and drop the `-wasm`.

2021-10-01 15:49 UTC, DyrellC commented on bindings/wasm/src/author/authorw.rs
> +            },
Probably doesn't hurt to throw one more `clippy` in there too just in case.

2021-10-01 15:49 UTC, DyrellC commented on iota-streams-core/src/sponge/spongos.rs
> +    pub fn into_inner(&self) -> Result<Inner<F>> {
That seems like a change for a later time/different PR, probably good to just revert this back for now and we'll do that self consumption thing in it's own PR just to keep the separation of concerns in check :sweat_smile:

2021-10-04 15:19 UTC, arnauorriols commented on bindings/wasm/Cargo.toml
> +name = "streams_wasm"
ok, let's discuss this further in the context of the release

2021-10-04 15:21 UTC, merged