[v2.0] Introduce UserBuilder
iotaledger/streams pull request #214
Opened 2022-03-24 21:11 UTC by DyrellC

# Description of change
Introduces the `UserBuilder` for user creation and separates the difference between `Author` and `Subscriber` instances. All user api functionality is consolidated to just the `/api/tangle/user.rs` file, and the `UserBuilder` can be used to generate the instance using a `UserIdentity` as its foundation. 

The examples have also been consolidated with the removal of `ChannelType`.  

## Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested
- Examples for `SingleBranch` and `SingleDepth` have been removed, and `MultiBranch` continues to execute to completion
- Clippy and fmt passed locally 

## Change checklist
- [] I have followed the contribution guidelines for this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2022-03-30 00:00 UTC, kwek20 requested changes
Therse still branching type examples etc in the documentations. That should be removed as well :)
Or did we decide not to do that?

2022-03-30 22:13 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +/// ## Author from Seed
I am also in favor of moving them somewhere else. I'm not particularly fond of it either, but with @arnauorriols  working on the testing structure I thought it best to just keep with this formatting until we can migrate it elsewhere.

2022-03-30 22:14 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +pub struct UserBuilder<Trans: Transport, F> {
Hmmmmm I don't think we've really discussed that... it would change the way we fetch Psk's. It might make the most sense to have a user with multiple Psk's store them outside of the builder still 🤔  @arnauorriols  what do you think on this front?

2022-03-30 22:16 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    id: UserIdentity<F>,
I prefer the former, a `User` can't really be built without an `Identity` so we'd either have to error out on build, or just pass the `Identity` in through the build command, and i'm more in favor of the latter.

2022-03-30 22:16 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    transport: Trans,
A good point, I can update that

2022-04-05 20:33 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    transport: Trans,
In order to do so I had to make some adjustements, like using an option for `Transport` to allow for `default()`.

2022-04-05 20:34 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +            user: crate::api::User::gen(take(&mut self.id), take(&mut self.alias), self.auto_sync),
I've made changes to make `api::User::gen()` accept the builder.

2022-04-05 20:35 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> -        let user = UserImp::gen(id, channel_type, ENCODING.as_bytes().to_vec(), PAYLOAD_LENGTH);
I think you're correct, so I've moved recover into the builder as well, and made `User::gen()` accept the builder for pulling parameters.

2022-04-05 20:36 UTC, DyrellC commented
As for the naming of the example, I'd like to change that as well, but what would we like to migrate it to?

2022-04-12 15:39 UTC, arnauorriols requested changes
+540 -1968 is quite satisfactory! 😄 I have some comments here and there, most of them around the builder "injection" into `User::gen()` and its implications. Nothing really difficult to address, but it definitely requires some alignment discussion.

2022-04-12 15:39 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +/// ## Author from Seed
Ok, first of all, these are not meant to read in the code 😂 2.0 will be released to crates.io, and with it, its documentation will also be released in docs.rs. 

Secondly, these comments are the API reference, and as such, they are very strongly encouraged to include examples to show users consuming the API reference a quick example of how the method is used, in order to understand its nuances and imagine it in practice. The wiki is another type of documentation, that includes tutorials, explanations and how-twos. Those are bigger examples that show how to accomplish different goals with Streams as a whole, but you cannot expect every method to be exemplified in there. That's what the API reference is for, and the API reference is written in code comments. I have the intention to prepare an style document that includes several sources with recommendations on how to write proper documentation in Rust libraries, but for now I'll share this basic one, the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/documentation.html) to start getting an idea. 

I recommend you to browse some crates to how it should actually look like:
- [rand](https://docs.rs/rand/latest/src/rand/rng.rs.html#55-303)
- [csv](https://github.com/BurntSushi/rust-csv/blob/master/src/reader.rs)
- [reqwest](https://docs.rs/reqwest/latest/src/reqwest/async_impl/response.rs.html)

> This is also hard to maintain as tests dont cover them

precisely because tests do cover them, these are easier to maintain than wiki examples. And as said, examples in wiki (let alone the examples in the `/examples` directory) serve another purpose. Actually, it's been proven by the received feedback that the examples in `/examples` does not serve any documentative purpose at all, only as tests (and not as good as proper tests should).

One aspect I do agree is questionable is their verbosity, particularly in the case of the `messages.rs` module, for the sake of actually being able to use them also as tests, and having to mask the use of the `BucketTransport`. Alternatively, we could chose on a test-by-test basis if we write them also as tests, or we skip them (with the `no_run` anotation). But that would make the not-runned potentially unmaintained.

2022-04-12 15:39 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +/// ```
This documentation should be moved to the type, instead of the implementation, shouldn't it? Also, try giving it some structure, as suggested in the [rustdoc book](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#documenting-components). Keep in mind that the first sentence is also what is shown when listing the type in the parent module. 

Lastly, I don't think the examples should be dealing with any sort of sending any message, even if hidden underthehood for testing purposes. Unit tests of the `UserBuilder` should test specifically what the builder does, to build users, as simple as it sounds. Anyway, keep in mind that first and foremost, these are documentation examples, not tests. We should write them always with a documentation mindset, not a testing mindset. Their testing nature is a nice by-product but not their main goal. By that I mean that we should write proper tests besides the documentation examples, and we have to make sure that the documentation examples actually serve their purpose by rendering the documentation and checking the result.

2022-04-12 15:39 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    pub fn build(&mut self) -> User<Trans> {
As suggested in another comment, I think the signature should be `fn build(self) -> User<Trans>` (or `fn build(self) -> Result<User<Trans>>` if we are expecting any error case).

2022-04-12 15:39 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +            transport: self.transport.unwrap().clone(),
It is a basic rule of Rust good practices to never clone on behave of users. If we know we need ownership of something, we have to take ownership of it and let the user decide if and when to clone the data. Besides the signature of `with_transport()`, it is for this reason that generally the `build()` method takes ownership of `self`, otherwise the configuration parameters need to be cloned, violating the good practice. See the [API guidelines](https://rust-lang.github.io/api-guidelines/flexibility.html#caller-decides-where-to-copy-and-place-data-c-caller-control)

2022-04-12 15:47 UTC, arnauorriols commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +pub struct UserBuilder<Trans: Transport, F> {
I think if we consider multiple PSK, we should consider it as supporting multiple identities in general, as @kwek20 suggests. Let's translate this proposal into a Github Discussion and we'll see how it pans out.

2022-04-12 16:36 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +            alias: builder.alias.take(),
That was the way it was before, @kwek20  expressed concern about managing it should the parameters of `User` building increase, but I suppose there is no avoiding those additions one way or another regardless of if they are injected at the `gen()` (or `new()` rather) or the `build()`.

2022-04-12 16:50 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +            transport: self.transport.unwrap().clone(),
This was essentially the way it was before, `Transport` would be cloned by the user into the builder, then the builder would consume it. Passing by reference reduced the need of a second `clone()`, but with a `self` consumption pattern the transport should only need the one  clone, and that's when user's are injecting it into the builder.

2022-04-12 19:48 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
> +pub trait Transport<Link, Msg>: TransportOptions + TransportDetails<Link> + Default {
The Default isn't necessary so I've removed it now. A fair point that we don't want to restrict Transport unnecessarily

2022-04-12 19:51 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> +    pub async fn new(seed: &str, transport: &Trans) -> Self {
I was curious about everyones thoughts on this as well. We discussed a couple times during our planning that we wished to go back to a synchronous process, but we also discussed having some quick api tools at the highest level for ease of use in simple use cases (like for example making a subscriber for a public channel). 

With that being said though i'm more in favor of removing these kinds of builder pattern skipping methods and just establish a standard of using the `Builder` as the `User` constructor in all cases. Like you said, it's not saving much verbosity wise.

2022-04-20 09:29 UTC, arnauorriols requested changes
Looking much better. The comments on this round are mostly stylistic. Besides the compiler and linter warnings that need attending, there's a warning from `cargo doc`:

```
 Documenting iota-streams-app-channels v0.1.2 (/home/orriols/dev/iota/streams/iota-streams-app-channels)
warning: unresolved link to `api::tangle::Author`
 --> iota-streams-app-channels/src/lib.rs:3:53
  |
3 | //! API functions can be found through the [Author](api::tangle::Author) and
  |                                                     ^^^^^^^^^^^^^^^^^^^ no item named `Author` in module `tangle`
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: unresolved link to `api::tangle::Subscriber`
 --> iota-streams-app-channels/src/lib.rs:4:18
  |
4 | //! [Subscriber](api::tangle::Subscriber)
  |                  ^^^^^^^^^^^^^^^^^^^^^^^ no item named `Subscriber` in module `tangle`

warning: `iota-streams-app-channels` (lib doc) generated 2 warnings
```

2022-04-20 14:49 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +    pub fn new(user_id: UserIdentity<F>, alias: Option<UserIdentity<F>>, auto_sync: bool) -> Self {
Reasonable enough, the auto_sync is also not really being used anywhere though. Do we not want that in there yet either?

2022-04-20 15:53 UTC, DyrellC commented on iota-streams-app/src/transport/tangle/client.rs
> +        let did_client = block_on(
correct

2022-04-20 15:53 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +            // If UserId is None in builder, gen should panic
It does not

2022-04-20 17:06 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +            user: crate::api::ApiUser::new(self.id.unwrap(), self.alias, self.auto_sync),
changed

2022-04-20 17:07 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
>              user.store_psk(pskid, user.user.user_id.psk().unwrap()).unwrap();
It makes more sense for it to be in User yeah, I've updated it.

2022-04-20 17:11 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    ///
I've gone through all the examples and removed the extra spaces, the formatting took a little getting used to.

2022-04-20 17:41 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +    /// announcement message with the provided User configuration, or should the the provided
Aside from the double `the` and lower case `user` what are the "bunch of them"? I've reworked it anyways to remove the `Transport` requirement part, so you might want to give it another pass over and see if there's still anything that jumps out at you.

2022-04-20 18:45 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user_builder.rs
> +pub struct UserBuilder<Trans: Transport, F> {
After our discussion today it looks like we'll save this issue for another PR where we separate logic for PSK's from Identity logic

2022-04-21 18:36 UTC, kwek20 commented on iota-streams-app-channels/src/api/user.rs
> +        // TODO: Remove different channel types, encoding and uniform payload
What do you mean with this TODO here?

2022-04-21 18:37 UTC, kwek20 approved these changes

2022-04-21 19:33 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        // TODO: Remove different channel types, encoding and uniform payload
Ah yes that should be gone now, channel types are gone already and encoding and uniform payload are hardcoded

2022-04-22 06:45 UTC, arnauorriols approved these changes
We are good to go from my end!

2022-04-22 06:47 UTC, merged