Draft: Feat/permissions
iotaledger/streams pull request #223
Opened 2022-03-29 16:28 UTC by kwek20

# Description of change

Adds permissions to subscribers for each branch

Currently checks for ReadWrite permissions and otherwise read-only. 
Timed write does not function yet, and BranchAdmin is the same as ReadWrite permissions.

Currently implemented using the DID implementation style, with implementing `sizeof`, `wrap` and `unwrap`

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Open questions:

1. What would be the default permission for a user (`prepare_keyload_for_everyone`) Currently at `Read`
2. Do we allow someone with BranchAdmin permissions to change the author permissions. Currently author is always allowed.
3. How do we handle TaggedPacket? Currently all are accepted.
4. Better idea on storing permissions? (keep in mind lean and non-lean state) Currenly its a map of (KL link: Permissions), and a map of (link: KL link)

## Todo (In another PR)
- Implement actual PermissionDuration
- Reduce import/export size of permissions hashmaps by referencing ids with index instead clone
- Move permissions hashmaps to a separate store (possibly merge keystore and linkstore)

## How the change has been tested

- Added a new permissions example
- Updated old examples adding an extra check in the recovery example

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-29 22:21 UTC, DyrellC commented
> What would be the default permission for a user (prepare_keyload_for_everyone) Currently at Read

I believe Read/Write due to the function itself being meant as a high level utility function to avoid having to actually define the `subscribers`/`psks` specifically. With that being said though I would follow this question up with another: Do we want to retain this function in the future considering the new api does not have it specified? We just have `branch` specified with specific declarations of the permissions for each user.

2022-03-29 22:22 UTC, DyrellC commented
> Do we allow someone with BranchAdmin permissions to change the author permissions. Currently author is always allowed.

I think it makes sense to have Author be the super user essentially and their permissions shouldn't be changable. For example, if a Subscriber is given admin priveleges over a branch but then the author chooses to revoke those administrative priveleges at a later time, the subscriber would be able to shut out the author's ability to do so if they can't write/admin the branch themselves as well. Although dropping the channel super user administration could have its advantages in a decentralised ecosystem, I still think that it makes sense to retain it.

2022-03-30 22:10 UTC, DyrellC requested changes
Round 1 done here. Main points of interest are the `Permissions` removal comment, structuring for `KeyStore`/`BranchStore`, and the `TaggedPacket` comment.

2022-03-30 22:10 UTC, DyrellC commented on iota-streams-app/src/permission.rs
> +impl core::convert::TryFrom<Vec<u8>> for Permission {
This function isn't used anywhere from what I saw

2022-03-30 22:10 UTC, DyrellC commented on iota-streams-app/src/permission.rs
> +use crate::{
I think it would make sense for this file to be in the `id` directory along with `identifier.rs`

2022-03-30 22:10 UTC, DyrellC commented on iota-streams-app/src/id/identifier.rs
> +impl core::convert::TryFrom<Vec<u8>> for Identifier {
This function isn't used either (except by the unused `Permission::try_from()` function)

2022-03-31 12:13 UTC, arnauorriols reviewed
Here's my first batch of comments. I'm missing the review of `api/user.rs`, but gotta change context for a while and don't want to keep the PR waiting!

2022-03-31 14:21 UTC, kwek20 commented on examples/src/branching/permissions.rs
> +    println!("\nTagged packet 1 - SubscriberB (tagged is always allowed)");
Its not signed, how would you verify the sender? We dont currently check it actually, but we should!

2022-03-31 14:34 UTC, kwek20 commented on examples/src/branching/permissions.rs
> +    println!("\nTagged packet 1 - SubscriberB (tagged is always allowed)");
I mean we could just verify based on sender id anyways, but if you can fake it, whats the point?

2022-03-31 14:38 UTC, kwek20 commented on examples/src/branching/permissions.rs
> +    println!("\nSigned packet 1 - SubscriberB (subscriber B does NOT has Write permission");
Ive left it as Signed packet X - User. Corrected numbering

2022-03-31 14:38 UTC, kwek20 commented on examples/src/branching/permissions.rs
> +        match subscriberA.receive_signed_packet(&previous_msg_link).await {
hmm yes agreed, ill change the permissions test for this

2022-03-31 15:46 UTC, DyrellC commented on iota-streams-app-channels/src/api/key_store.rs
> +    pub fn filter<'a, I>(&self, ids: I) -> Vec<(Permission, Vec<u8>)>
Agreed, although if we should still address the fact that this is an unused function right now

2022-03-31 15:47 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/author.rs
> +    pub async fn send_keyload<'a, I>(&mut self, link_to: &Address, keys: &'a I) -> Result<(Address, Option<Address>)>
Yes I was referring to the `&'a I` addition.

2022-04-07 17:01 UTC, kwek20 commented on iota-streams-app-channels/src/api/tangle/author.rs
> +    pub async fn send_keyload<'a, I>(&mut self, link_to: &Address, keys: &'a I) -> Result<(Address, Option<Address>)>
yea i was trying to avoid too many clones. Youre right though that its just a byte. Ill change it and we will probably improve it on the keystore write anyway

2022-04-07 18:19 UTC, kwek20 commented on examples/src/branching/recovery.rs
> +            if let Some(seq) = seq {
as long as we do, this is useful for debugging

2022-04-07 18:21 UTC, kwek20 commented on iota-streams-app-channels/src/api/tangle/author.rs
> +    pub async fn send_keyload<'a, I>(&mut self, link_to: &Address, keys: &'a I) -> Result<(Address, Option<Address>)>
Ive reverted it, now relying on an into_iter().copied().collect(). Not pretty either but the best for now until keystore rewrite

2022-04-07 18:22 UTC, kwek20 commented on iota-streams-app-channels/src/api/user.rs
> +    pub(crate) keyloads: HashMap<Link, Link>,
it looks alright from a usage perspective imo `permissions.get(keyloads.get(link))`

2022-04-08 13:16 UTC, kwek20 commented on iota-streams-app-channels/src/api/key_store.rs
> +    pub fn filter<'a, I>(&self, ids: I) -> Vec<(Permission, Vec<u8>)>
Actually filter worked fine still, ive switched back to using it

2022-04-08 13:37 UTC, kwek20 commented on iota-streams-app/src/message/link.rs
> +pub trait HasLink: Sized + Default + Clone + Eq + Hash {
Its used in hashmap yes, seems like a good case to have impl in general for the link.
The only alternative is doing the link.to_bytes() and storing that... seems less efficient and uglier

2022-04-08 13:52 UTC, kwek20 commented on iota-streams-app/src/permission.rs
> +use crate::{
Moved

2022-04-12 22:36 UTC, DyrellC commented on examples/src/branching/permissions.rs
> +    println!("\nTagged packet 1 - SubscriberB (tagged is always allowed)");
The issue on my side isn't about the verifying side of things, it's about being allowed to send something at all if you're `ReadOnly`. If they're set to `Read`, other User's shouldn't be able to find any messages from them anyways, so why would we allow them to send them in the first place? If an `Author` defines that `SubA` is `Read` in `Branch1` then if `SubA` tries to publish on their end and they don't receive any sort of warning or error, they won't know that everyone else in `Branch1` isn't looking for their messages anyways and they'll get lost in the ether.

2022-04-25 23:52 UTC, DyrellC reviewed
Looking good to me, just a couple of small questions and a trait we can probably do without and I think she's good to go.

2022-04-25 23:52 UTC, DyrellC commented on examples/src/branching/recovery.rs
> +    latest_link = &previous_msg_link;
Is there a particular benefit to this reassignment as opposed to just having latest link be the assignment for the received link?

2022-04-25 23:52 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        match res {
Is there a reason for handling the response here as opposed to in line 507 and 517 and having this function accept the WrappedMessage not wrapped in a result?

2022-04-25 23:52 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        &mut self,
Why this `mut`?

2022-04-25 23:52 UTC, DyrellC commented on iota-streams-app/src/id/identifier.rs
> +impl core::convert::TryFrom<Vec<u8>> for Identifier {
I think this is still a thing, the `TryFrom` implementation here doesn't seem to be used anywhere. The `Permission::try_from()` was removed but this one is still here with no purpose. We should be able to remove this one as well.

2022-04-26 10:22 UTC, kwek20 commented on examples/src/branching/recovery.rs
> +    latest_link = &previous_msg_link;
yes, to not use the previous "run" but purely use the recovered instance

2022-04-26 10:25 UTC, kwek20 commented on iota-streams-app-channels/src/api/user.rs
> +        match res {
sure, didnt feel like doing the `match res` twice. ill revert

2022-05-04 22:32 UTC, arnauorriols requested changes
It's a go from my side, once the example/test passes!

2022-05-05 19:18 UTC, arnauorriols approved these changes

2022-05-05 19:23 UTC, merged