Style Guide and Diataxis Review: Streams V
iotaledger/streams pull request #228
Opened 2022-03-31 11:25 UTC by charlesthompson3

# Description of change

TW Style guide and diataxis review applied to streams documentation. Sections reviewed include:

- Specs
- Troubleshooting
- Contribute

## Type of change

- Documentation Fix

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have made corresponding changes to the documentation

2022-03-31 11:25 UTC, charlesthompson3 commented
@iotaledger/tech-writers

2022-03-31 11:55 UTC, lucas-tortora commented on documentation/docs/contribute.md
> +Take a look at what discussions are going on in the #experience channel on [Discord](https://discord.com/channels/397872799483428865/701857063923351582).
```suggestion
Take a look at what discussions are going on in the [#experience channel on Discord](https://discord.com/channels/397872799483428865/701857063923351582).
```

2022-03-31 11:55 UTC, lucas-tortora commented on documentation/docs/specs.md
> +for sending data over a given transport layer.
```suggestion
description: The Streams framework is intended to be a secure message verification and protection protocol for sending data over a given transport layer.
```
If the description is on more than one line it'll crash docusuarus

2022-03-31 11:55 UTC, lucas-tortora commented on documentation/docs/specs.md
>  ---
We could delete this file altogether and add an external link to the pdf in the sidebar, wdyt?

Example:
 {
    type: 'link',
    label: 'Specs',
    href: 'https://github.com/iotaledger/streams/blob/develop/specification/Streams_Specification_1_0A.pdf',
  },

2022-03-31 14:46 UTC, aleksei-korolev requested changes

2022-03-31 14:46 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +**Thanks for thinking about contributing to the project! Below are some ways that you can contribute.**
```suggestion
Thanks for thinking about contributing to the project! Below are some ways that you can contribute.
```
It's already in the front of the article, so no extra emphasis is needed.

2022-03-31 14:46 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +- Code samples.
Maybe convert it into a plain sentence?

2022-03-31 14:46 UTC, aleksei-korolev commented on documentation/docs/contribute.md
> +If you would like to get involved, join the #experience channel on [Discord](https://discord.com/channels/397872799483428865/701857063923351582).
```suggestion
If you would like to get involved, join the `#experience` channel on [Discord](https://discord.com/channels/397872799483428865/701857063923351582).
```

2022-03-31 14:46 UTC, aleksei-korolev commented on documentation/docs/specs.md
>  ---
This will the be an unexpected file download, which will also take the user away from the wiki. IMO it is better to have an extra step which will prepare the user.

2022-04-01 05:21 UTC, charlesthompson3 commented on documentation/docs/specs.md
> +for sending data over a given transport layer.
👍

2022-04-01 05:24 UTC, charlesthompson3 commented on documentation/docs/specs.md
>  ---
I agree with the idea of getting rid of or supplementing a one line section and putting it somewhere else. But I also agree with the "extra step"/heads up thing. At least for this audience.

2022-04-01 05:24 UTC, charlesthompson3 commented on documentation/docs/contribute.md
> +**Thanks for thinking about contributing to the project! Below are some ways that you can contribute.**
🤷👍

2022-04-01 09:18 UTC, lucas-tortora approved these changes

2022-04-01 09:55 UTC, aleksei-korolev approved these changes

2022-08-02 18:47 UTC, merged