[v2.0] Move psk store to user
iotaledger/streams pull request #237
Opened 2022-05-20 17:47 UTC by DyrellC

# Description of change
Moves the `psks` HashMap out of `KeyStore` and into `User` directly. 
- Keyloads now need specified psks when sending
- Keyloads iterate over provided psks and apply `Permissioned::Read` to each of them when masking key
- Identity::Psk and Identifier::Psk have been removed 

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested
- Examples updated
- Doc Tests updated

2022-05-25 15:24 UTC, DyrellC commented on lets/src/message/content.rs
> -    async fn encrypt_sizeof(&mut self, recipient: &T, exchange_key: &[u8], key: &[u8]) -> Result<&mut Self>;
Alright i'll bring it back as `_recipient`

2022-05-25 15:30 UTC, DyrellC commented on lets/src/id/identity.rs
>      pub fn _ke(&self) -> [u8; 32] {
It's simple enough I'll do it now, if only to avoid us potentially forgetting about it until later

2022-05-25 15:39 UTC, DyrellC commented on lets/src/id/permission.rs
> +impl Mask<&Permissioned<PskId>> for sizeof::Context {
When wrapping and unwrapping a user we need to wrap and unwrap `psk_store`. So `Absorb` could be used instead if `Mask` seems excessive, but I do believe we can't avoid having them.

2022-05-25 15:40 UTC, DyrellC commented on streams/src/api/key_store.rs
>      keys: HashMap<Identifier, x25519::PublicKey>,
A good point, so we'll have `CursorStore`, `PskStore` and `KeyStore` as separate stores going forward. I agree though, lets save that for a separate PR of its own instead of shoehorning it here

2022-05-25 15:52 UTC, DyrellC commented on streams/src/api/key_store.rs
>      pub(crate) fn get_exchange_key(&self, identifier: &Identifier) -> Option<&[u8]> {
It's another one of those quick fixes so I did it

2022-05-25 15:53 UTC, DyrellC commented on streams/src/api/user.rs
> +    pub(crate) fn new(user_id: Identity, psks: &[(PskId, Psk)], transport: T) -> Self {
1. I was under the impression we wanted to allow users to define their own `PskId` if they so chose to, and if that's the case, we should be having them input them
2. I think that's reasonable, `Vec<Psk>` would make more sense ownership wise
3. That's probably the best possible implementation, kind of a best of both worlds scenario

2022-05-25 15:54 UTC, DyrellC commented on streams/src/api/user.rs
> +        self.state.psk_store.remove(&pskid).is_none()
That was definitely just an overlooked typo, not that we use that boolean value anywhere (which is why it flew under my radar)

2022-05-25 16:00 UTC, arnauorriols commented on lets/src/id/permission.rs
> +impl Mask<&Permissioned<PskId>> for sizeof::Context {
I meant the `Permissioned`. It does not make sense to have permissioned pskids, does it?

`Mask<&PksId>` is already implemented in `pks.rs`

2022-05-25 16:02 UTC, DyrellC commented on streams/src/api/user.rs
>              self.subscribers().map(Permissioned::Read).collect::<Vec<_>>(),
reasonable

2022-05-25 16:22 UTC, DyrellC commented on lets/src/id/permission.rs
> +impl Mask<&Permissioned<PskId>> for sizeof::Context {
Aaaaah, yes sorry misread the line you were commenting on. Correct it looks like we don't need to have these implementations at all. Remnants of an earlier bit of logic I was trying to keep `Subscribers` as one collection for keyloads.

2022-05-25 16:28 UTC, arnauorriols commented on streams/src/api/user.rs
> +    pub(crate) fn new(user_id: Identity, psks: &[(PskId, Psk)], transport: T) -> Self {
1. Hm, wasn't aware of this. What about collisions? In any case, there are various places in the code that assume pskids are derived from psks. I'd like @semenov-vladyslav opinion on the potential security implications on this

2022-05-25 16:36 UTC, DyrellC commented on streams/src/api/user.rs
> +    pub(crate) fn new(user_id: Identity, psks: &[(PskId, Psk)], transport: T) -> Self {
The world is simpler when making that assumption, but during our earlier discussions it was proposed to allow users to define their `PskId`. I'm fine with the approach of not if it's a security concern. Collisions shouldn't be unreasonable to deal with, `Psks` only have so much presence in the first place, so having an extra error if a `PskId` is already in use would suffice would it not?

2022-05-26 07:04 UTC, arnauorriols commented on streams/src/api/user.rs
> +    pub(crate) fn new(user_id: Identity, psks: &[(PskId, Psk)], transport: T) -> Self {
I suppose so. I've created a task to add proper support for user-defined PskId #241

2022-05-26 07:44 UTC, arnauorriols commented on streams/src/api/key_store.rs
> +    pub(crate) fn get_exchange_key(&self, identifier: &Identifier) -> Option<&x25519::PublicKey> {
Now that I see it, I realize this is now a duplicate of `KeyStore::get_key()`

2022-05-26 07:49 UTC, arnauorriols commented on streams/src/api/user.rs
> +        });
You could have left the for loop exactly as it where, why change it?
```suggestion
        for (pskid, psk) in psks {
            psk_store.insert(pskid, psk);
        }
```

2022-05-26 08:36 UTC, arnauorriols commented on streams/src/api/message.rs
> +        self.psks.iter().any(|id| id.eq(psk_id))
why use `eq()` instead of `==`?

2022-05-26 08:38 UTC, arnauorriols commented on streams/src/api/message.rs
>      pub fn includes(&self, subscriber: Identifier) -> bool {
now that we have `inculdes_psk`, to avoid confusion I'd call this `includes_subscriber`

2022-05-26 09:02 UTC, arnauorriols commented on streams/src/api/message.rs
> +            psks: keyload.psks().to_vec(),
This is one of those cases where lifetimes get in the way. In this case, cause the internal attributes of `Keyload` are not public, we cannot leverage partial moving of `psks` and `subscribers`. We cannot use `keyload.into_psks()` because that would move the whole `Keyload`. However, by doing `keyload.psks().to_vec()`, we are cloning the whole `Vec` unnecessarily. There are 2 options:
- make `psks` and `subscribers` fields `pub(crate)`. This would allow us to partially move them, but at the expense of starting to muddy the waters of the policy towards public vs private internal fields. 
- use the "take" pattern (see https://github.com/iotaledger/streams/blob/ab7e79e6fbf601218081da5b6f143fece2dc6c56/streams/src/message/signed_packet.rs#L117-L123), so that the vectors are replaced by an empty vector. This has the handicap that it still incurs in an unnecessary allocation, albeit of an empty vector, avoiding to clone its content. 

I don't have a preference, tbh.

2022-05-26 09:09 UTC, arnauorriols commented on streams/src/api/user_builder.rs
> +    pub psks: Vec<(PskId, Psk)>,
Why `pub`? Particularly in public types, I'd be very restrictive with what fields are public, instead of giving access to them via method (which in this case is not even necessary)

2022-05-26 09:30 UTC, arnauorriols commented on streams/src/api/user_builder.rs
> +    /// #   .with_transport(transport)
Why hide these 2 lines? It creates a "false" example that will confuse the user

2022-05-26 09:35 UTC, arnauorriols commented on streams/src/api/user_builder.rs
>      /// # let transport: Rc<RefCell<bucket::Client>> = Rc::new(RefCell::new(bucket::Client::new()));
Same here, we don't need to shadow the `tangle::Client` at all

2022-05-26 09:39 UTC, arnauorriols commented on streams/src/message/keyload.rs
> +            if let Some(psk) = keyload.psk_store.get(&psk_id) {
we could check here if the key has not yet been decrypted (`key.is_none()`), in order to avoid decrypting it multiple times unnecessarily

2022-05-26 14:36 UTC, DyrellC commented on streams/src/api/user.rs
> +        });
I assumed if there was an iterative process that using the iterator itself rather than a for loop was more appropriate. From what I saw (https://doc.rust-lang.org/book/ch13-04-performance.html) iterators are more performant so I assumed it was better to use them whenever possible over looping.

2022-05-26 14:50 UTC, DyrellC commented on streams/src/api/message.rs
> +            psks: keyload.psks().to_vec(),
I'm going to go with the `pub(crate)` direction on this one. `mem::take` would require `Keyload` to be `&mut` which complicates `MessageContent::From<keyload::unwrap>`

2022-05-26 14:51 UTC, DyrellC commented on streams/src/api/user_builder.rs
> +    pub psks: Vec<(PskId, Psk)>,
It doesn't actually need to be pub at all, not sure why I made it pub in the first place

2022-05-26 14:53 UTC, DyrellC commented on streams/src/api/user_builder.rs
> +    /// #   .with_transport(transport)
Fair points all around. I hid them because they seemed irrelevant to the demonstration of the `psks` but it could also have served to confuse someone into an incorrect implementation. I've replaced the transport with default as well.

2022-05-26 14:55 UTC, DyrellC commented on streams/src/api/user_builder.rs
>      /// # let transport: Rc<RefCell<bucket::Client>> = Rc::new(RefCell::new(bucket::Client::new()));
I've replaced the client with `with_default_transport().await?`

2022-05-30 12:02 UTC, arnauorriols commented on streams/src/api/user.rs
> +        });
ok! I doubt it's a meaningful performance improvement in this case, but nvm.

2022-05-30 12:06 UTC, arnauorriols approved these changes
Looking great. Just one old comment pending to address, but everything else is ready to merge in my opinion.

2022-05-30 19:34 UTC, arnauorriols commented on streams/src/api/user.rs
> +    pub(crate) fn new(user_id: Identity, psks: &[(PskId, Psk)], transport: T) -> Self {
I think we can live with the inconsistency for the time being, no biggie.

2022-05-31 00:02 UTC, kwek20 requested changes
Am i correct in thinking we dont really need PskId anymore? We should remove it in that case

2022-05-31 00:38 UTC, DyrellC commented
@kwek20 https://github.com/iotaledger/streams/issues/241 Arnau made this issue after this conversation: https://github.com/iotaledger/streams/pull/237#discussion_r885048616. What's your opinion?

2022-05-31 00:39 UTC, DyrellC commented on lets/src/id/identifier.rs
> +                let oneof = Uint8::new(1);
Agreed

2022-05-31 00:41 UTC, DyrellC commented on streams/src/api/user.rs
>      pub async fn send_keyload_for_all_rw(&mut self, link_to: MsgId) -> Result<SendResponse<TSR>> {
I think it's worth addressing when we get to the high level API rewrite, because defining the `Permissions` more directly will make more sense semantically once `send_keyload` assumes the new `change_permissions()` definition

2022-05-31 15:11 UTC, kwek20 approved these changes
I'll leave a comment on the issue regarding PskId, as this PR is just moving it, it can be done in a new one. (if we decide to remove it)

2022-05-31 15:12 UTC, merged