[v2.0] Move exchange keys into User
iotaledger/streams pull request #251
Opened 2022-05-31 15:36 UTC by DyrellC

# Description of change
Remove exchange key management from `KeyStore` and rename to `CursorStore`. Exchange keys will now be hosted inside the `User` for now (will be removed later once #245 is addressed). 

Addresses: #240 

## Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested
- examples and tests continue to run with changes
- cargo fmt/clippy/test

2022-06-01 14:49 UTC, arnauorriols approved these changes
All good! I would say something about the method naming of `CursorStore`, but I assume they will change again the topic PR

2022-06-02 00:49 UTC, kwek20 requested changes
lets clean this,  then good to go!

2022-06-02 00:49 UTC, kwek20 commented on streams/src/api/user.rs
> +        let keys = user_state.exchange_keys.iter().map(|(id, xkey)| (id, xkey));
same for here

2022-06-02 17:51 UTC, DyrellC commented on streams/src/api/user.rs
> +        let keys = user_state.exchange_keys.iter().map(|(id, xkey)| (id, xkey));
Yes, yes we can

2022-06-02 18:02 UTC, DyrellC commented on streams/src/api/user.rs
> +        let keys = user_state.exchange_keys.iter().map(|(id, xkey)| (id, xkey));
done

2022-06-02 18:08 UTC, merged