[V2.0] Track Permissions Through Topics
iotaledger/streams pull request #270
Opened 2022-07-12 20:04 UTC by DyrellC

# Description of change
Currently the only place we use `Permissioned` is when we are doing checks on `Keyload` messages, but those permissions are not retained in store anywhere, as our cursor store only uses the Identifier. To allow for that permission retention we need to change `CursorStore` to map by `Permissioned<Identifier>` instead of just `Identifier`. This brings a host of other trickling changes along with it. 

For example, a `User` will be able to check their permissions on a topic before they attempt to send messages, failing if they are registered as `Read` by a topic administrator. Additionally administrative privileges can be properly assigned and forwarded through the topics. 

Requires #262 to be merged 

## Type of change
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested
New section added to end of examples to have `Author` re-subscribe `SubscriberA` and grant them Admin privileges, confirming that they carry forward into new branches. 
- All previous examples complete
- All previous tests complete

2022-07-26 09:17 UTC, arnauorriols commented on streams/examples/full-example/scenarios/basic.rs
> +    let result = subscriber_a
The comment can be removed now, right?

2022-08-02 15:21 UTC, kwek20 requested changes
On my end, the tangle test fails at did.rs:143

2022-08-02 15:21 UTC, kwek20 commented on streams/src/api/user.rs
> +                    Permissioned::Admin(s.clone())
What is this step for? Just for admin to be able to check his permissions?

2022-08-05 17:00 UTC, DyrellC commented on lets/src/id/permission.rs
> +        self.mask(&permission.take())
Yes that does make more sense, changed

2022-08-05 17:03 UTC, DyrellC commented on streams/src/api/user.rs
> +        let stored_subscribers: Vec<(Topic, Permissioned<Identifier>, usize)> = self
We can and should yes

2022-08-05 17:05 UTC, DyrellC commented on streams/src/api/user.rs
> +                    .insert_cursor(&topic, Permissioned::Read(perm.identifier().clone()), cursor);
It's either this or removing them, which would reset their cursor standing, so I think it's appropriate to retain the cursor but in a state that it won't be used to iterate new messages unless added again in a later keyload by the Author.

2022-08-05 17:08 UTC, DyrellC commented on streams/src/api/user.rs
> +                    Permissioned::Admin(s.clone())
For admin to establish that they will continue to be admin going forward and not replace their permissions with a read/write

2022-08-05 17:31 UTC, DyrellC commented on lets/src/id/permission.rs
> +    pub fn take(self) -> Permissioned<Identifier> {
I was grappling between the two honestly so no problem changing that to clone

2022-08-05 17:32 UTC, DyrellC commented on lets/src/id/permission.rs
> +    pub fn take(self) -> Permissioned<Identifier> {
Ah I remember now why I chose take, if it's not an actual clone implementation clippy does not like it

2022-08-08 14:26 UTC, kwek20 commented on streams/src/api/user.rs
> +                    .insert_cursor(&topic, Permissioned::Read(perm.identifier().clone()), cursor);
To me, if youre not included in the keyload yoou shouldnt have access to the data.
I know we said that keyloads carry on through branches, but i wasnt thinking on a additive manner, same keyload or new keyload only. Lets see waht @arnauorriols thinks about this

2022-08-08 14:33 UTC, kwek20 commented on lets/src/id/permission.rs
> +    pub fn take(self) -> Permissioned<Identifier> {
lets implement a From trait instead then, i think it looks better.

```
impl From<Permissioned<&Identifier>> for Permissioned<Identifier> {
    fn from(permisison: Permissioned<&Identifier>) -> Self {
        match permisison {
            Permissioned::Read(id) => Permissioned::Read(id.clone()),
            Permissioned::ReadWrite(id, duration) => Permissioned::ReadWrite(id.clone(), duration),
            Permissioned::Admin(id) => Permissioned::Admin(id.clone()),
        }
    }
}
```

2022-08-18 09:22 UTC, arnauorriols commented on streams/src/api/user.rs
> +                    .insert_cursor(&topic, Permissioned::Read(perm.identifier().clone()), cursor);
>  which would reset their cursor standing

Oh! I also thought it was weird not to remove the cursor, but you are right, we need to keep the cursor around in case the user is added to the branch again. 

> To me, if youre not included in the keyload yoou shouldnt have access to the data

This does not change. the user that is not included in the keyload cannot decode the message, period. The fact that it remains tracked is to keep the cursor around. It would probably be less confusing if instead of using the permissions, we had a type that expressed this intent explicitly

2022-08-22 16:32 UTC, kwek20 approved these changes
LGTM!

2022-08-22 16:33 UTC, merged