[V2.0] Docs update
iotaledger/streams pull request #282
Opened 2022-09-30 23:07 UTC by DyrellC

# Description of change
Updating documentation across all crates. 
- [ ] wiki 
- [ ] readme's 
- [ ] streams
- [ ] lets
- [ ] spongos

## Type of change
- Documentation Fix

2022-10-09 01:14 UTC, kwek20 requested changes

2022-10-09 01:14 UTC, kwek20 commented on streams/src/api/user_builder.rs
> +    /// If a [`Transport`] is not provided the builder will use a default client.
```suggestion
    /// If a [`Transport`] is not provided, the builder will use a default client.
```

2022-10-09 01:14 UTC, kwek20 commented on streams/src/message/unsubscription.rs
> +    /// Returns a reference to the [`Identifier`] of the subsriber
```suggestion
    /// Returns a reference to the [`Identifier`] of the subscriber
```

2022-10-12 04:16 UTC, DyrellC commented on lets/src/message/version.rs
> +pub(crate) const STREAMS_1_VER: u8 = 1;
I was running on habit to not update versions until we're pushing the release

2022-10-12 04:19 UTC, DyrellC commented on streams/src/api/mod.rs
> +pub mod message_builder;
It is, and I agree.

2022-10-12 04:20 UTC, DyrellC commented on streams/src/api/mod.rs
> +pub mod message_builder;
Alternative is to remove all links to `MessageBuilder` and `Messages` which makes the `User` docs more rigid

2022-10-13 22:50 UTC, kwek20 commented on lets/src/message/version.rs
> +pub(crate) const STREAMS_1_VER: u8 = 1;
Fair enough!

2022-10-13 22:51 UTC, kwek20 approved these changes
LGTM! Whats the plan with wiki and readme? we will do that in another pr?

2022-10-17 22:18 UTC, merged