[V2.0] error handling WIP
iotaledger/streams pull request #283
Opened 2022-10-03 15:44 UTC by kwek20

# Description of change

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [] I have followed the contribution guidelines for this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2022-10-07 06:29 UTC, DyrellC requested changes
I think the whole DID wrapping enum can be removed by using the `ToString` approach for converting the identity errors. Aside from that it's mostly suggestions on potential improvements to readability and messaging.

2022-10-07 06:29 UTC, DyrellC commented on lets/src/transport/tangle.rs
> +            .map_err(|e| Error::IotaClient("sending message", e))?
This and the one below are a little inconsistent. Should probably stick to either 
`"sending message" and "receiving messages"` or `"send_message" and "recv_message"` with the appropriate change to the `Error::IotaClient` message syntactically

2022-10-07 06:29 UTC, DyrellC commented on spongos/src/error.rs
> +    #[error("here was an issue with the calculated signature, cannot unwrap message")]
```suggestion
    #[error("There was an issue with the calculated signature, cannot unwrap message")]
```

2022-10-07 06:29 UTC, DyrellC commented on spongos/src/error.rs
> +    #[error("Generating context {0} failed due to {1}")]
I think this is the most confusing error to understand as is. In most implementations it reads like this: 
`Generating context ContentVerify failed due to [error]` which doesn't really make any sense. We should probably rephrase it to something along the lines of 

 ```suggestion
    #[error("Context failed to perform the message command \"{0}\"; Error: {1}")]
```

This way it would read `Context failed to perform the message command "ContentVerify"; Error: [error]`

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +        "address already taken for. The address '{1}' where the {0} message is being sent already contains some data, possibly spam."
```suggestion
        "Address already taken. The address '{1}' where the {0} message is being sent already contains some data, possibly spam."
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("unexpected message type {0}")]
```suggestion
    #[error("Unexpected message type {0}")]
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("message '{0}' not found in {1}")]
```suggestion
    #[error("Message '{0}' not found in {1}")]
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("Failed getting messages for {0} due to {1}")]
```suggestion
    #[error("Failed to get messages.  Error: {0}")]
```
I don't think we need to specify which function caused this error, it'll already be traced

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    MissingUserData(&'static str, &'static str, &'static str),
This is never used from what I've seen

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +        "user does not have a cursor in branch '{0}'. This probably means the user does not have write permission over that branch"
```suggestion
        "User does not have a cursor stored in branch '{0}'. This probably means the user does not have write permission within that branch"
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("the user does not have an identity, but needs one to {0}")]
```suggestion
    #[error("User does not have an identity, but needs one to {0}")]
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("User identity contained no secret key")]
```suggestion
    #[error("User identity contains no secret key")]
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +        "not connected to a stream. A user must either create a stream or connect to an existing one before attempting to {0}"
```suggestion
        "Not connected to a stream. A user must either create a stream or connect to an existing one before attempting to {0}"
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +        "Message not linked. The {0} message at address '{1:#?}' is not linked to any message. \
```suggestion
        "Message not linked. The {0} message at address '{1:#?}' is not linked to a previous message. \
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +Any {0} message must be linked to a previous message by including the address of the previous message in the header"
```suggestion
Any {0} message must be linked to a previous message by including the address of the existing message in the header"
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("topic {0} not found in store")]
```suggestion
    #[error("Topic {0} not found in store")]
```

2022-10-07 06:29 UTC, DyrellC commented on streams/src/error.rs
> +    #[error("Transport error whilest doing {0} for address {1}: {2}")]
```suggestion
    #[error("Transport error while trying to {0} for address {1}; Error: {2}")]
```

2022-10-13 16:15 UTC, kwek20 commented on spongos/src/error.rs
> +    #[error("Generating context {0} failed due to {1}")]
Yea this one was a hard one, as it feels unneeded but needs to be thrown from the spongos error throughout streams/lets

2022-10-13 18:21 UTC, kwek20 commented on lets/src/id/did/url_info.rs
> +        let utf =
Its more specific now but maybe a bit over the top

2022-10-17 16:57 UTC, merged