Merge user and transport instances
iotaledger/streams pull request #36
Opened 2020-09-26 21:42 UTC by DyrellC

This PR is to introduce a merging of transport and user api's to reduce the number of steps needed by the users to utilise Streams functionality. It takes the transport layer and pulls it into the User object so that users only need to use one set of API tools rather than individual Transport and User instances:

- All send and receive functions are enacted through the wrapping/unwrapping api
- Links and sequence states will only be stored if a message is properly sent through the transport layer
- Added Rc to core::prelude 
- Author and Subscriber API's updated to use links instead of messages
- Moved fetching logic from examples utility to tangle API instances
- Examples updated with new api arguments

2020-09-27 16:38 UTC, semenov-vladyslav requested changes
There's a few issues that need to be addressed:
- Transport: Rc/RefCell, async, Options, impl for c bindings
- logic behind fetch_next_msgs and MsgInfo type

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/mod.rs
> +pub enum MsgInfo {
This stuff is really tangle specific. Message info is some auxiliary data associated to a link stored in `link_store`. It allows to keep a list of recipients for Keyload message, signer public key for SignedPacket or app-specific data. `MsgInfo` is just an enum because it's difficult to think of a good enough generic type for channels app.

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +type AuthorImp<T> = User<DefaultF, Address, LinkGen, LinkStore, PkStore, PskStore, T>;
Shall we introduce some default transport? How otherwise do we implement c bindings?

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +    pub fn fetch_next_msgs(&mut self) -> Result<Vec<(ed25519::PublicKey, Address, Bytes, Bytes)>> {
What is the return type?

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +            let msg = (&*self.imp.transport).borrow_mut().recv_message_with_options(&link, &self.imp.recv_opt);
`msg` is of `Result` type, maybe there's a better name?

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +            if msg.is_ok() {
Do we just skip the error as there's no else branch? Why?

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +                        _ => {
We don't handle other types of messages? Keyload for example?

2020-09-27 16:38 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/author.rs
> +                            let content = self.unwrap_signed_packet(next_link.clone())?;
If unwrap fails here for some reason we are going to lose all `msgs` handled by this moment. Is that ok?

2020-09-27 16:38 UTC, semenov-vladyslav commented on examples/src/branching/utils.rs
> +        let msgs = author.fetch_next_msgs().unwrap();
`unwrap` will `panic` if there's an error.

2020-09-27 16:43 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/user.rs
> +    pub(crate) transport: Rc<RefCell<T>>,
I actually think that it's best to split `User` into tangle `User` part that will contain api `User` and transport and will handle sending/recving messages. And we can maybe get rid off of `handle_xxx` methods from api `User`.

2020-09-28 16:15 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/user.rs
> +    pub(crate) transport: Rc<RefCell<T>>,
Also, should we implement transport as `Box<dyn Transport>` to hide transport type from type signature and allow transport polymorphism?

2020-09-29 05:17 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +    pub(crate) transport: Rc<RefCell<T>>,
To address the top part we'll be doing the Default Transport implementation, so we should be able to avoid the need to actually use Rc and RefCell altogether. Those are only necessary fro the example purposes and don't really make sense in a production environment. Brord should be tackling that right now. 

As for the second point, we'll be moving the Transport up into the Tangle layer with that new User implementation wrapping the Auth/Sub instance with the transport and a simplified/symmetric api (Hurray).

2020-09-29 05:19 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +    pub(crate) recv_opt: <T as transport::Transport<F, Link>>::RecvOptions,
Brord should be on top of this one, but we'll be using this approach to set and get the recv and send options. They should (in most implementations) just be the defaults, but for those using private tangles with a reduced mwm for example will need the ability to set what those "defaults" would actually be.

2020-09-29 05:19 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
>      ) -> Result<BinaryMessage<F, Link>> {
This, and others have been set to return links now.

2020-09-29 05:20 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        (&*self.transport).borrow_mut().send_message_with_options(&wrapped.message, &self.send_opt)?;
We'll have to address async post release but it is indeed a thing we need to address in the future. For now it should be noted that Users are expected to track their message sent status themselves for async. Handling sync states may need to be made into a callback to be handled on a future completion, but we'll address that later.

2020-09-29 05:21 UTC, DyrellC commented on iota-streams-app-channels/src/api/user.rs
> +        link: Link,
This problem is essentially present everywhere not just with announce. We now will have a handle message function that will automate this process though.

2020-09-29 05:22 UTC, DyrellC commented on iota-streams-app/src/transport/mod.rs
> +#[derive(Clone)]
Removed

2020-09-29 05:29 UTC, DyrellC commented on iota-streams-app-channels/src/api/mod.rs
> +pub enum MsgInfo {
This is moved up into the tangle layer again

2020-09-29 09:14 UTC, semenov-vladyslav requested changes
Most importantly deal with `User` struct, the current design is dubious. Also need to deal with `Result` and not just skip errors.

2020-09-29 09:14 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/user.rs
> +pub struct User<Trans, U>
Where is this `User` going to be used? Does `U` stand for `Author` or `Subscriber` from `tangle` module? Is it going to be used as a top entity and `Author` and `Subscriber` become implementation details?

2020-09-29 09:14 UTC, semenov-vladyslav commented on iota-streams-app-channels/src/api/tangle/user.rs
> +pub struct User<Trans, U>
I had a slightly different idea instead:
```
mod api { struct User }
mod tandle {
pub struct User<Tsp> {
    tsp: Tsp,
    user: api::User,
}
pub struct Author<Tsp> {
    user: User<Tsp>, // NOTE: User from tangle mod, not api
}
pub struct Subscriber<Tsp> {
    user: User<Tsp>, // NOTE: User from tangle mod, not api
}
}
```
This way `User`, `Author` and `Subscriber` stay the top-level entities, and we can nicely implement `IsUser`, `IsAuthor` and `IsSubscriber` traits.

2020-09-29 15:22 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> +pub struct User<Trans, U>
So the main reason why there were the traits was to provide functionality that works between user types so we don't have to repeat everything. When we remove the traits and do struct implementations like this we get locked up into having to implement everything individually on each. Making the api a little more verbose than necessary. There is no api::User to pull in for example, we can only pull in api::user::User, which is the api implementation, not a superclass of Author and Sub, so because of that we would be directly injecting the Author/Sub implementation into the User rather than using the Tangle api layer at all. If user::User was a trait being applied then it would maybe make sense. The idea of the implementation I wrote up here was to act as a Top entity that takes in either an Author or Subscriber, and the Auth and Subs use the traits to use the base layer functionality present in the tangle::User class.

User gets used as the baseline implementation when setting up your instance, and depending on whether you load in an Author or Subscriber implementation you will be restricted to using the functions present in the traits for those specifically. So it also provided the separation of powers for functionality. A User with an Author injected can use the functions present in the UserImp trait, but also the AuthUser trait, but not the SubUser trait. 

As is I don't really see how to apply it the way you want here because there is no "inheritable" trait to apply these structs to that wouldn't require us to rewrite how the Author and Sub are used right now.

2020-09-29 20:07 UTC, DyrellC commented on iota-streams-app-channels/src/api/tangle/user.rs
> +                    let _unwrapped = self.user.unwrap_keyload(msg);
This is checked inside the api user now, it'll return a bool if you are part of the keyload or not. If a different failure occurs then it will fail out (with the change from Option to Result for the return).

2020-10-01 07:14 UTC, semenov-vladyslav approved these changes

2020-10-01 07:14 UTC, merged