Update c bindings, add new functions
iotaledger/streams pull request #50
Opened 2020-11-09 18:53 UTC by DyrellC

# Description of change
Updating c bindings to include tagged and signed packets on the subscriber end, as well as a couple utility functions for usability (like converting string link representation to proper streams Address object through bindings).

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
I have run each function through modifications of the main.c file, and confirmed they work when pulled into golang

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

2020-11-11 18:47 UTC, semenov-vladyslav requested changes
Update `main.c` to cover the new functions.

2020-11-11 18:47 UTC, semenov-vladyslav commented on bindings/c/src/api/mod.rs
> +        let addr = Address::from_str(addr_vec[0], addr_vec[1]).unwrap();
`addr_vec[1]` will panic if address doesn't contain a colon, need to add a guard. 

`unwrap()` in general can panic, need better handling of unwraps throughout all streams repo, not only bindings. In c bindings we can return nulls.

2020-11-11 18:47 UTC, semenov-vladyslav commented on bindings/c/src/api/mod.rs
> +pub extern "C" fn new_message_links(msg_link: *const Address, seq_link: *const Address) -> *mut MessageLinks {
No need to make an explicit function, `message_links_t` struct is defined in `channels.h` and can be constructed directly in c.

2020-11-11 18:47 UTC, semenov-vladyslav commented on bindings/c/src/api/mod.rs
> +        CString::new(hex::encode((*address).msgid.as_ref())).unwrap().into_raw()
Shall we check pointers for `null`, or hope/expect caller code doesn't violate convention?

2020-12-02 17:53 UTC, kwek20 commented on bindings/c/CMakeLists.txt
> +option(STATIC "Build shared library" OFF)
ahyes we should rename this and maybe decide on what we make as default, we keep swapping it aboot

2020-12-03 21:47 UTC, DyrellC commented on bindings/c/src/api/mod.rs
> +        CString::new(hex::encode((*address).msgid.as_ref())).unwrap().into_raw()
Hmmm a good question really. I think it's fair to expect that they'll not violate the conventions, but it probably doesn't hurt to catch the strays and save them the seg fault

2020-12-03 21:48 UTC, DyrellC commented on bindings/c/src/api/mod.rs
> +        let addr = Address::from_str(addr_vec[0], addr_vec[1]).unwrap();
Will map_or them to ensure null returns wherever a panic could occur

2020-12-03 21:49 UTC, DyrellC commented on bindings/c/CMakeLists.txt
> +option(STATIC "Build shared library" OFF)
We should default to Shared since static is still giving us grief

2020-12-07 18:51 UTC, kwek20 approved these changes
LGTM!

2020-12-08 18:46 UTC, semenov-vladyslav requested changes
Looks good, but move impl of `address_from_string` into main crate?

2020-12-08 18:46 UTC, semenov-vladyslav commented on bindings/c/src/api/mod.rs
> +pub extern "C" fn address_from_string(c_addr: *const c_char) -> *const Address {
This is a nice function in general, it's going to be used in other bindings. Maybe move the impl to the main crate?

2020-12-08 20:14 UTC, DyrellC commented on bindings/c/src/api/mod.rs
> +pub extern "C" fn address_from_string(c_addr: *const c_char) -> *const Address {
Yeah I think that's a good idea, i'll do that before push

2020-12-09 01:06 UTC, merged