(fix/bindings) Updated web and node only examples
iotaledger/streams pull request #84
Opened 2021-04-20 15:16 UTC by kwek20

# Description of change

Fixes https://github.com/iotaledger/streams/issues/83

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Ran examples found in README in `bindings/wasm`

2021-04-28 09:14 UTC, dominic22 commented on bindings/wasm/examples/node.js
> +  let options2 = new streams.SendOptions(1, 9, true, 1);
It seems like the constructor of SendOptions has parameters. I've got also an error for this line in typescript.

From the iota_streams_wasm.d.ts:
```
export class SendOptions {
/**
* @param {number} depth
* @param {boolean} local_pow
* @param {number} threads
*/
  constructor(depth: number, local_pow: boolean, threads: number);
```

2021-04-28 09:17 UTC, dominic22 requested changes

2021-04-28 09:17 UTC, dominic22 commented on bindings/wasm/examples/node.js
> +  let options = new streams.SendOptions(1, 9, true, 1);
It seems like the constructor of SendOptions has parameters. I've got also an error for this line in typescript.

From the iota_streams_wasm.d.ts:
```
export class SendOptions {
/**
* @param {number} depth
* @param {boolean} local_pow
* @param {number} threads
*/
  constructor(depth: number, local_pow: boolean, threads: number);
```

2021-04-28 09:17 UTC, dominic22 commented on bindings/wasm/examples/node.js
> +  let sub = new streams.Subscriber(node, seed2, options2, false);
For the Subscriber the parameters are also different as in the code of line 34. 

From the iota_streams_wasm.d.ts:


```
export class Subscriber {
  ...
/**
* @param {string} node
* @param {string} seed
* @param {SendOptions} options
*/
  constructor(node: string, seed: string, options: SendOptions);
```

2021-04-28 09:17 UTC, dominic22 commented on bindings/wasm/examples/node.js
> +  let sub = new streams.Subscriber(node, seed2, options2, false);
I don't know if the last parameter is now part of the options. Could you please adjust this?

2021-04-28 14:25 UTC, dominic22 commented on bindings/wasm/examples/node.js
> +  let masked_payload = to_bytes("Masked");
These payloads also have a different type as the method `send_tagged_packet` is expecting.

2021-04-30 14:12 UTC, kwek20 commented on bindings/wasm/examples/node.js
> +  let masked_payload = to_bytes("Masked");
Just change `to_bytes` first line into `Uint8Array[str.length]` and solved. I suppose thats what you did

2021-04-30 14:13 UTC, kwek20 commented on bindings/wasm/examples/node.js
> +  let sub = new streams.Subscriber(node, seed2, options2, false);
You can remove the `false` as subscribers get that boolean from the author announce message now

2021-05-03 08:03 UTC, dominic22 approved these changes

2021-05-03 12:29 UTC, merged