WASM: Add Stateless Recovery and Listen
iotaledger/streams pull request #98
Opened 2021-06-09 22:29 UTC by DyrellC

# Description of change
Add listen and recover functions to Wasm Bindings. These updates are intended to emulate previous MAM behaviour.

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
Examples have been updated to include functionality for testing

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-09 22:47 UTC, kwek20 requested changes
We should really change it so that the user doesnt need to call .clone() on auth and sub. We can do this ourselves inside the methods right? Or am i missing something

2021-06-09 22:47 UTC, kwek20 commented on bindings/wasm/src/lib.rs
> +pub async fn wait(ms: u32) {
Replace this with `await new Promise(r => setTimeout(r, ms));`

2021-06-10 06:34 UTC, DyrellC commented on bindings/wasm/src/lib.rs
> +pub async fn wait(ms: u32) {
I tried to do that first and ran into a whole host of issues trying to import the function. In order to use `setTimeout()` we need it to build the js function in commonjs not ES6, which wasm-bindgen doesn't support (see https://rustwasm.github.io/wasm-bindgen/reference/js-snippets.html#caveats). So building this for Web target is fine, but not for nodejs. We could look at using the Closures instead maybe? https://rustwasm.github.io/wasm-bindgen/reference/passing-rust-closures-to-js.html

2021-06-10 06:43 UTC, DyrellC commented on bindings/wasm/src/lib.rs
> +pub async fn wait(ms: u32) {
I'm not sure we can avoid the `clone()` either, since the js functions consume the author or subscriber instance given to them (or so is my understanding) so the `clone()` is done to pass a new instance of Author/Subscriber with a copy of the `Rc<RefCell<ApiAuthor/ApiSubscriber>>`. If you try to pass by reference instead of by static object the compiler complains that `me` doesn't live long enough.

2021-06-21 14:41 UTC, kwek20 commented on bindings/wasm/src/lib.rs
> +pub async fn wait(ms: u32) {
@DyrellC I figured out a way, can you confirm they work for you as well?
I can both `build:nodejs` and `build:web`

2021-09-07 23:11 UTC, DyrellC commented
@kwek20  The `.clone()` removal is in https://github.com/iotaledger/streams/pull/140, and i've removed the listen function, now it's just stateless recovery, and it looks like it's good to go as soon as it's approved here.

2021-09-16 17:25 UTC, arnauorriols commented on bindings/wasm/src/author/authorw.rs
> +    #[wasm_bindgen(catch)]
unnecessary

2021-09-16 17:27 UTC, arnauorriols commented on bindings/wasm/src/subscriber/subscriberw.rs
> +    #[wasm_bindgen(catch)]
idem

2021-09-16 17:27 UTC, arnauorriols commented on bindings/wasm/examples/node.ts
> +<<<<<<< HEAD
Fix conflict

2021-09-16 17:28 UTC, DyrellC commented on bindings/wasm/examples/node.ts
> +<<<<<<< HEAD
Doing that now actually, caught it right after i pushed :sweat_smile:

2021-09-16 17:28 UTC, DyrellC commented on bindings/wasm/src/author/authorw.rs
> +    #[wasm_bindgen(catch)]
accurate

2021-09-16 17:29 UTC, arnauorriols reviewed
Good to go once you fix the git conflict!

2021-09-16 17:33 UTC, arnauorriols approved these changes

2021-09-16 17:37 UTC, DyrellC commented
Alright conflict fixed up and attributes removed @arnauorriols

2021-09-16 17:52 UTC, merged